sitejess/routes/web.php
<?php

use App\Http\Controllers\admin\adminArticleArtisanController;
use App\Http\Controllers\admin\adminMagasinController;
use App\Http\Controllers\Magasin_controller;
use App\Http\Controllers\admin\UsersController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Magasin;
use App\Artisan;
use App\Evenement;
use App\Mail\Contact;
use Gloudemans\Shoppingcart\Facades\Cart;
use PHPUnit\Runner\Hook;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/',function(Request $request){
    return redirect()->route('caroussel.index');
});


//Route::group([],function(){


// Ca on garde
// mes routes pour l'ajout des articles
 Route::get('/create/{id_magasin}/article', 'Magasin_controller@createArticle');
 Route::post('/shop/{id_magasin}/article/store', 'Magasin_controller@storeArticle');
// Route pour la modification de l'article
 Route::get('/edit/{id_article}/{id_magasin}/article', 'Magasin_controller@editArticle');
 Route::put('/shop/{article}/article/update', 'Magasin_controller@updateArticle')->name('update_article');
 // route pour la suppression des articles
 Route::delete('/shop/{article}/article/delete','Magasin_controller@destroyArticle')->name('delete_article');

 // route pour les categorie
 
// c'est ton controlleur qui va encaisser toutes les routes
Route::resource('/shop','Magasin_controller');

// c'est ton controlleur qui va encaisser toutes les routes pour l'ajout de la categorie a propos de nous
Route::resource('/A_propos','Propo_controller');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Routes pour Artisan
Route::get('artisan','ArtisanController@index')->name('artisan.index');
Route::get('artisan/{id}','ArtisanController@show')->name('artisan.show');

// 2 route pour le formulaire de contact :
        Route::get('contact/create', 'Contact_controller@create')->name('contact.formulaire');
        Route::post('contact/store', 'Contact_controller@store')->name('contact.store');
        Route::get('contact/confirm', 'Contact_controller@confirm')->name('contact.confirm');
   
// route search
Route::get('search','SearchController@search')->name('shop.search');
// routes pour les evenements
Route::resource('/evenement','EvenementController');

// route pour la boutique
Route::resource('/boutique','ProduitController');
Route::get('/boutique/{slug}','ProduitController@show')->name('product.show');

Route::group(['middleware'=>['auth']],function(){
    // route pour les cartes
Route::get('/mon-panier','CartController@index')->name('cart.index');
Route::post('/panier/ajouter','CartController@store')->name('cart.store');
Route::patch('/panier/{rowId}','CartController@update')->name('cart.update');
Route::delete('/panier/{rowId}','CartController@destroy')->name('cart.destroy');
});
Route::group(['middleware'=>['auth']],function(){
// routes des checkout
Route::get('/paiement','CheckoutController@index')->name('checkout.index');
Route::post('/paiement','CheckoutController@store')->name('checkout.store');
Route::get('/merci','CheckoutController@thankyou')->name('checkout.merci');
});


// Route pour l'affichage du caroussel
Route::get('/accueil','CarousselController@affichecarou')->name('caroussel.index');

// Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
        Route::resource('users','UsersController');
        Route::resource('/shop','adminMagasinController');
        Route::resource('/evenement','adminEventController');
        Route::resource('/A_propos','adminPropoController');
        Route::resource('/contact','adminContactController');
        Route::resource('/article','adminArticleArtisanController');
        Route::get('contact/confirm','adminContactController@confirm')->name('contact.confirm');
        Route::resource('/caroussel','AdminCarousselController');
        Route::get('/',function(){
            return view('master.maitre_admin');
        });
        Route::get('/create/{id}/article', 'adminMagasinController@createArticle')->name('article.create.article');
        Route::post('/shop/{id}/article/store', 'adminMagasinController@storeArticle')->name('article.store.article');
       // Route pour la modification de l'article
        Route::get('/edit/{id}/{magasin_id}/article', 'adminMagasinController@editArticle')->name('article.edit.article');
        Route::put('/shop/{article}/article/update', 'adminMagasinController@updateArticle')->name('article.update.article');
        // route pour la suppression des articles
        Route::delete('/shop/{article}/article/delete','adminMagasinController@destroyArticle')->name('article.delete.article');
        Route::resource('/artisan','adminArtisanController');
        Route::get('/welcome','AdminCarousselController@affichecarou')->name('afficheCarou');
        Route::get('/search','SearchAdminController@searchAdmin')->name('search.search');
    
});

sitejess/resources/views/shop/search.blade.php
@extends('master/maitre')
@section('content')
{{-- blade pour la barre de recherche du Site  --}}
<div class="container">
    <div class="row">

        @foreach($mag as $shop)
            <div class="col-4 card" style="margin-right: 0%">
                <img src="{{ url($shop->image) }}" class="card-img-top " alt="image" width="50%">
                {{-- <div class="card-body" > --}}
                <h3><strong><a
                            href="{{ url('/shop/' . $shop->id) }}">{{ $shop->nom }}</a></strong>
                </h3>
                <p class="text-truncate">{{ $shop->description }}</p>
                <p> categorie : {{ $shop->categorie }}</p>
                <p class="card-text"><small class="text-muted">Ajouter le :
                        {{ $shop->created_at->format('d/m/y') }}</small></p>
                {{-- </div> --}}
            </div>
        @endforeach


        @foreach($eve as $event)
            <div></div>
            <div class="col-4 card">
                <img src="{{ url($event->image) }}" class="card-img-top " alt="image">
                <div>
                    <h3><strong><a
                                href="{{ url('/evenement/'.$event->id) }}">{{ $event->nom }}</a></strong>
                    </h3>
                    <p class="text-truncate">{{ $event->description }}</p>
                    <p> categorie : Evenement</p>
                    <p class="card-text"><small class="text-muted">Ajouter le :
                            {{ $event->created_at->format('d/m/y') }}</small></p>
                </div>

            </div>
        @endforeach

        @foreach($art as $artisan)
            <div class=""></div>
            <div class="col-4 card">
                <img src="{{ url($artisan->image) }}" class="card-img-top " alt="image">
                <div>
                    <h3><strong><a
                                href="{{ url('artisan/'.$artisan->id) }}">{{ $artisan->nom }}</a></strong>
                    </h3>
                    <p class="text-truncate">{{ $artisan->description }}</p>
                    <p> categorie : Créateurs Locaux</p>
                    <p class="card-text"><small class="text-muted">Ajouter le :
                            {{ $artisan->created_at->format('d/m/y') }}</small></p>
                </div>

            </div>
        @endforeach
        @foreach($pro as $produit)

            {{-- <div > --}}
            <div class="card-form m-0  col-4">
                <div class="card">
                    <img src="{{ $produit->image }}" alt="image" class="card-img-top">
                    {{-- <div class="card-body"> --}}
                    <h3><strong class="">World</strong></h3>
                    <h5 class="card-title">{{ $produit->title }}</h5>
                    <div class=" card-text">
                        <p> <small
                                class="text-muted">{{ $produit->created_at->format('d/m/y') }}</small>
                        </p>
                    </div>
                    <p class="card-text">{{ $produit->subtitle }}</p>
                    <strong class="card-text">{{ $produit->getPrice() }}</strong><br>
                    <a href="{{ route('boutique.show',$produit->slug) }}"
                        class="card-text">voirl'article</a>

                    {{-- </div> --}}

                </div>
            </div>
            {{-- </div> --}}


        @endforeach

    </div>

</div>
</div>

@endsection

sitejess/resources/views/shop/shop.blade.php
@extends('master/maitre')
@section('content')
{{-- cette blade me permet d'afficher mes magasins --}}
<div class="container">
    <div class="row">
        @foreach($shops as $shop)
            <div class="card-form m-0 col-md-4 col-sm-6">
                <div class="card">
                    <img src="{{ url($shop->image) }}" class="card-img-top " alt="image">
                    <div class="card-body">
                        <h5 class="card-title"><strong><a
                                    href="{{ url('shop/'.$shop->id) }}">{{ $shop->nom }}</a></strong>
                        </h5>
                        <div style="max-height: 200px">
                            <p class="text-truncate " style="max-width: 400px;">{{ $shop->description }}</p>
                        </div>
                        <p class="card-text">Ajouter le : <small
                                class="text-muted">{{ $shop->created_at->format('d-m-Y') }}</small>
                        </p>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
</div>
@endsection

sitejess/resources/views/shop/shop_show.blade.php
@extends('master/maitre')
@section('content')
{{-- blade des articles de chaque Magasin --}}
<div class="container">
    <div>
        <div>
            <h3 style="text-align: center">{{ $shop->nom }}</h3>
            <div class="row div-img">
                <div class="col-lg-8" style="justify-content:center;">
                    
                  <p style="margin-bottom: 0%; margin-top:5%" class="">{{ $shop->description }}</p><br>
                  <p style="margin-top: 5%"> <strong>Horaire d'ouverture :</strong> </p>
                  @foreach($shop ->horaires as $jour)
                          <p style="margin-bottom:0%">
                              {{ $jour->jours }} :
                              @if($jour->fermer)
                                  fermé
                              @else
                                  {{ $jour->hor_ouverture->format('H:m')}}-
                                  @if($jour->hor_fer_mat){{ $jour->hor_fer_mat->format('H:m')}} @endif
                                  @if($jour->hor_deb_aprem){{ $jour->hor_deb_aprem->format('H:m') }} @endif
                                  {{ $jour->hor_fermeture->format('H:m')}}
                              @endif
                          </p>
                  @endforeach
                </div>
                <div class="col-lg-4 ">
                    <img src="/{{ $shop->image }}" class="img-fluid " style=" margin-bottom:10%; margin-top:10%" >
                    <p style="margin-top: 5%"> <strong>L'adresse du magasin :</strong> </p>
                  <p>{{ $shop->geolocalisation->adresse }}</p>
                    <p> {{ $shop->site }} </p>
                    <p>{{ $shop->facebook }}</p>
                    <p>{{ $shop->instagram }}</p>   
                </div>
            </div>
        </div>
        <h2 style="margin-top: 10%; text-align: center">Les Articles</h2>
        <div class="row">
        @foreach($shop->articles as $article)
            <div class="column col-4">
                <article>
                    <h4 style="margin-top: 10%; text-align: center ">{{ $article->titre_article }}</h4>
                    <img class="img-fluid rounded mx-auto d-block" src="{{ url($article->image_article) }}" width="320px">
                    <p>{{ $article->description_article }}</p>
                </article>
            </div>
        @endforeach
        </div>
    </div>
</div>
</div>

@endsection