sitejess/routes/web.php
<?php

use App\Http\Controllers\admin\adminArticleArtisanController;
use App\Http\Controllers\admin\adminMagasinController;
use App\Http\Controllers\Magasin_controller;
use App\Http\Controllers\admin\UsersController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Magasin;
use App\Artisan;
use App\Evenement;
use App\Mail\Contact;
use Gloudemans\Shoppingcart\Facades\Cart;
use PHPUnit\Runner\Hook;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/',function(Request $request){
    return redirect()->route('caroussel.index');
});


//Route::group([],function(){


// Ca on garde
// mes routes pour l'ajout des articles
 Route::get('/create/{id_magasin}/article', 'Magasin_controller@createArticle');
 Route::post('/shop/{id_magasin}/article/store', 'Magasin_controller@storeArticle');
// Route pour la modification de l'article
 Route::get('/edit/{id_article}/{id_magasin}/article', 'Magasin_controller@editArticle');
 Route::put('/shop/{article}/article/update', 'Magasin_controller@updateArticle')->name('update_article');
 // route pour la suppression des articles
 Route::delete('/shop/{article}/article/delete','Magasin_controller@destroyArticle')->name('delete_article');

 // route pour les categorie
 
// c'est ton controlleur qui va encaisser toutes les routes
Route::resource('/shop','Magasin_controller');

// c'est ton controlleur qui va encaisser toutes les routes pour l'ajout de la categorie a propos de nous
Route::resource('/A_propos','Propo_controller');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Routes pour Artisan
Route::get('artisan','ArtisanController@index')->name('artisan.index');
Route::get('artisan/{id}','ArtisanController@show')->name('artisan.show');

// 2 route pour le formulaire de contact :
        Route::get('contact/create', 'Contact_controller@create')->name('contact.formulaire');
        Route::post('contact/store', 'Contact_controller@store')->name('contact.store');
        Route::get('contact/confirm', 'Contact_controller@confirm')->name('contact.confirm');
   
// route search
Route::get('search','SearchController@search')->name('shop.search');
// routes pour les evenements
Route::resource('/evenement','EvenementController');

// route pour la boutique
Route::resource('/boutique','ProduitController');
Route::get('/boutique/{slug}','ProduitController@show')->name('product.show');

Route::group(['middleware'=>['auth']],function(){
    // route pour les cartes
Route::get('/mon-panier','CartController@index')->name('cart.index');
Route::post('/panier/ajouter','CartController@store')->name('cart.store');
Route::patch('/panier/{rowId}','CartController@update')->name('cart.update');
Route::delete('/panier/{rowId}','CartController@destroy')->name('cart.destroy');
});
Route::group(['middleware'=>['auth']],function(){
// routes des checkout
Route::get('/paiement','CheckoutController@index')->name('checkout.index');
Route::post('/paiement','CheckoutController@store')->name('checkout.store');
Route::get('/merci','CheckoutController@thankyou')->name('checkout.merci');
});


// Route pour l'affichage du caroussel
Route::get('/accueil','CarousselController@affichecarou')->name('caroussel.index');

// Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
        Route::resource('users','UsersController');
        Route::resource('/shop','adminMagasinController');
        Route::resource('/evenement','adminEventController');
        Route::resource('/A_propos','adminPropoController');
        Route::resource('/contact','adminContactController');
        Route::resource('/article','adminArticleArtisanController');
        Route::get('contact/confirm','adminContactController@confirm')->name('contact.confirm');
        Route::resource('/caroussel','AdminCarousselController');
        Route::get('/',function(){
            return view('master.maitre_admin');
        });
        Route::get('/create/{id}/article', 'adminMagasinController@createArticle')->name('article.create.article');
        Route::post('/shop/{id}/article/store', 'adminMagasinController@storeArticle')->name('article.store.article');
       // Route pour la modification de l'article
        Route::get('/edit/{id}/{magasin_id}/article', 'adminMagasinController@editArticle')->name('article.edit.article');
        Route::put('/shop/{article}/article/update', 'adminMagasinController@updateArticle')->name('article.update.article');
        // route pour la suppression des articles
        Route::delete('/shop/{article}/article/delete','adminMagasinController@destroyArticle')->name('article.delete.article');
        Route::resource('/artisan','adminArtisanController');
        Route::get('/welcome','AdminCarousselController@affichecarou')->name('afficheCarou');
        Route::get('/search','SearchAdminController@searchAdmin')->name('search.search');
    
});

sitejess/app/Artisan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Artisan extends Model
{
    
    protected $fillable = ['id','nom','marque','description','site','facebook','instagram','image'];

    public function articles(){
        return $this->hasMany('App\Article');
    }
    public function caroussel(){
        return $this->belongsTo('App\Caroussel','artisan_id');
    }
}

sitejess/app/Http/Controllers/ArtisanController.php
<?php

namespace App\Http\Controllers;

use App\Artisan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;

class ArtisanController extends Controller
{
    public function __construct()
    {
        //  
    }
// fonction pour l'affichage des créateurs locaux
    public function index(){
        $artisans = Artisan::all();
        // return Session::all();
        return view('artisan/artisan',compact('artisans'));
    }
// fonction pour l'affichage des articles de chaque créateur locale
    public function show($id){
        $artisan = Artisan::findOrFail($id);
        return view('artisan/show',['artisan'=>$artisan]);
    }
}

sitejess/resources/views/admin/artisan/artisanAdmin.blade.php
@extends('master/maitre_admin')
@section('content')
<div class="container">
    <div class="column">

        <div>
            <a href="{{ route('admin.artisan.create') }}">Nouvel Artisan</a>
        </div>

        

        <div class="row">
            @foreach($artisans as $artisan)
                <div class="card-form m-0 w-50 col-md-4 col-sm-6">
                    <div class="card">
                        <img src="{{ url($artisan->image) }}" class="card-img-top " alt="image">
                        <h5 class="card-title"><strong><a
                                    href="{{ url('admin/artisan/' . $artisan->id) }}">{{ $artisan->nom }}</a></strong>
                        </h5>
                        <p class="text-truncate" style="max-width: 400px;">{{ $artisan->description }}</p>
                        <p class="card-text">Ajouter le : <small
                                class="text-muted">{{ $artisan->created_at->format('d-m-Y') }}</small>
                        </p>

                        <div class="d-flex justify-content-end">
                            <div>
                                <a href="{{ route('admin.artisan.edit',['artisan'=>$artisan]) }}"
                                    class="btn btn-success">
                                    editer</a>
                            </div>
                            <form
                                action="{{ route('admin.artisan.destroy',['artisan' => $artisan]) }}"
                                onsubmit="return confirm('Voulez Vous vraiment supprimer cette ce créateur')";
                                method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-outline-danger">supprimer</button>
                                @isset($message)
                                    <p>{{ $message }}</p>
                                @endisset
                            </form>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>
@endsection

sitejess/resources/views/admin/artisan/artisanShowAdmin.blade.php
@extends('master/maitre_admin')
@section('content')
<div class="container">
    <a
        href="{{ route('admin.article.create',['artisan'=>$artisan->id]) }}">Ajouter
        Article</a>

    <div>
        <div>
            <h3 style="text-align: center">{{ $artisan->nom }}</h3>
            <div class=" div-img ">
                <div class=" div-ext-art" >
                    <p>{{ $artisan->marque }}</p>
                    <p>{{ $artisan->description }}</p>

                    <h5 style="margin-bottom: 0%">Les liens externes</h5><br>
                    <a href="{{ $artisan->site }}" style="margin-bottom: 0%; margin-top:0%">
                        <p style="margin-bottom: 0%; margin-top:0%" target="_blank">{{ $artisan->site }}</p><br>
                    </a>
                    <a href="{{ $artisan->facebook }}">
                        <p style="margin-top: 0%; margin-bottom:0%" target="_blank">{{ $artisan->facebook }}</p>
                    </a> <br>
                    <a href="{{ $artisan->instagram }}">
                        <p style="margin-top: 0%; margin-bottom:15%" target="_blank">{{ $artisan->instagram }}</p>
                    </a>


                </div>
                <img src="{{ url($artisan->image) }}" class="img-art" alt="article-image" >
            </div>



        </div>

        <h3 style="margin-bottom: 10%; margin-top:10%; text-align:center">Les Articles</h3>
      <div class="row">
        @foreach($artisan->articles as $article)
            
                <div class="col-md-6 col-sm-12 col-lg-4">
                    <h5 style="text-align: center;">{{ $article->titre_article }}</h5>
                    <img src="{{ url($article->image_article) }}" alt="article-image" width="50%"
                        class="rounded mx-auto d-block">
                    <p style="text-align: center;">{{ $article->description_article }}</p>
                    <div class=" column" style="align-items: center">
                        <form action="{{ route('admin.article.destroy',$article->id) }}"
                            onsubmit="return confirm('Voulez Vous vraiment supprimer cette article')";
                            method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-outline-danger">supprimer Article</button>
                        </form>
                        <a href="{{ route('admin.article.edit',$article->id) }}"
                            class="btn btn-success"> Modifier l'article</a>
                    </div>
                </div>
            
        @endforeach
    </div>
  </div>
</div>
@endsection

sitejess/resources/views/admin/artisan/create.blade.php
@extends('master/maitre_admin')
@section('content')
<div class="container">
    <div class="card">
        <form action="{{route('admin.artisan.store')}}"  method="POST" enctype="multipart/form-data">
            @csrf
            <h3>Nouvel Artisan</h3>
            @error('nom')
                <p>{{ $message }}</p>
            @enderror
            <div class="form-group">
                <input type="text" name="nom" id="nom" class="form-control" placeholder="nom du createur">
            </div>
            @error('marque')
                <p>{{ $message }}</p>
            @enderror
            <div class="form-group">
                <input type="text" name="marque" id="marque" class="form-control" placeholder="marque">
            </div>
            @error('description')
                <p>{{ $message }}</p>
            @enderror
            <div>
                <textarea name="description" id="description" class="form-control" placeholder="votre description" rows="10"></textarea>
            </div>

            @error('image')
                <p>{{ $message }}</p>
            @enderror
            <div class="form-group">
                <label for="exampleFormControlFile1">choisissez une image</label>
            <input name="image" type="file" class="form-control-file" id="exampleFormControlFile1">
            </div>
            @error('site')
                <p>{{ $message }}</p>
            @enderror
            <div class="form-group">
                <input type="text" name="site" id="site" class="form-control" placeholder="site">
            </div>
            @error('facebook')
                <p>{{ $message }}</p>
            @enderror
            <div class="form-group">
                <input type="text" name="facebook" id="facebook" class="form-control" placeholder="facebook">
            </div>
            @error('instagram')
                <p>{{ $message }}</p>
            @enderror
            <div class="form-group">
                <input type="text" name="instagram" id="instagram" class="form-control" placeholder="instagram">
            </div>
            <button type="submit" class="btn btn-success">Enregistrer</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>

</div>
@endsection

sitejess/resources/views/admin/artisan/create_article.blade.php
@extends('master/maitre_admin')
@section('content')
{{-- form to add Articles--}}
<form action="{{route('admin.article.store',['artisan'=>$artisan])}}" method="POST" enctype="multipart/form-data">
    @csrf
    <h1>Nouvel Article</h1>
    <div class="form-group">
        <input type="text" name="titre_article" class="form-control" placeholder="titre de l'article ">
    </div>

<div>
<textarea name="description_article" class="form-control" placeholder="votre description" rows="10"></textarea>
</div>
<div class="form-group">
<label for="exampleFormControlFile1">Choisissez votre image</label>
<input name="image_article" type="file" class="form-control-file" id="exampleFormControlFile1">
</div> 
    <div >
        <button type="submit" class="btn btn-success">Enregistrer</button>
        <button type="reset" class="btn btn-danger">Reset</button>
      </div>  
      </form>
      @endsection

sitejess/resources/views/admin/artisan/edit.blade.php
@extends('master/maitre_admin')
@section('content')
<div class="container">
    <h3>Modifier un artisan</h3>
    <div>
    <form action="{{route('admin.artisan.update',['artisan'=>$artisan])}}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            @error('nom')
                <p>{{ $message }}</p>
            @enderror
            <div class="form-group">
            <input type="text" name="nom" id="nom" class="form-control" placeholder="nom du createur" value="{{$artisan->nom}}">
            
            @error('marque')
                <p>{{ $message }}</p>
            @enderror
           
                <input type="text" name="marque" id="marque" class="form-control" placeholder="marque" value="{{$artisan->marque}}">
           
            @error('description')
                <p>{{ $message }}</p>
            @enderror
           
                <textarea name="description" id="description" class="form-control" placeholder="votre description" rows="10" >{{$artisan->description}}</textarea>
            

            @error('image')
                <p>{{ $message }}</p>
            @enderror
           
                <label for="exampleFormControlFile1">choisissez une image</label>
            <input name="image" type="file" class="form-control-file" id="exampleFormControlFile1">
           
            @error('site')
                <p>{{ $message }}</p>
            @enderror
           
                <input type="text" name="site" id="site" class="form-control" placeholder="site" value="{{$artisan->site}}">
         
            @error('facebook')
                <p>{{ $message }}</p>
            @enderror
         
                <input type="text" name="facebook" id="facebook" class="form-control" placeholder="facebook" value="{{$artisan->facebook}}">
       
            @error('instagram')
                <p>{{ $message }}</p>
            @enderror
          
                <input type="text" name="instagram" id="instagram" class="form-control" placeholder="instagram" value="{{$artisan->instagram}}">
            </div>
            <button type="submit" class="btn btn-success">Modifier</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </form>
    </div>
</div>
@endsection

sitejess/resources/views/admin/artisan/edit_article.blade.php
@extends('master/maitre_admin')
@section('content')
{{-- form to edit article --}}
<div class="container">
    <form action="{{route('admin.article.update',$article->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <h1>Modifier Article</h1>
        @isset($message)
        {{-- si ça passe ici c'est que la variable message existe --}}
        <p>Ceci est un message de la plus haute importance de Fire the Coder !</p>
        {{-- ici c'est le message que l'on vient de définir dans la methode
            update --}}
        <p>{{ $message }}</p>
        @endisset
    
        <div class="form-group" >
        <input type="text" name="titre_article" class="form-control" placeholder="titre article" 
        value="{{$article->titre_article}}"
         required>
         </div>
        {{-- <div class="form-group">
            <input type="text" name="adresse" class="form-control" placeholder="adresse du magasin">
        </div> --}}
       <div class="form-group">
            <textarea name="description_article" class="form-control" placeholder="votre description" rows="10" 
            value="{{$article->description_article}}">
                </textarea>
       </div>
       <div class="form-group">
            <label for="exampleFormControlFile1">Choose your product's image</label>
            <input name="image_article" type="file" class="form-control-file" id="exampleFormControlFile1">
        </div>
       <div class="form-group">
          <button type="submit" class="btn btn-outline-success">Enregistrer</button>
          <button type="reset" class="btn btn-danger">Reset</button>
        </div>
    </form>
</div>

@endsection