sitejess/routes/web.php
<?php

use App\Http\Controllers\admin\adminArticleArtisanController;
use App\Http\Controllers\admin\adminMagasinController;
use App\Http\Controllers\Magasin_controller;
use App\Http\Controllers\admin\UsersController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Magasin;
use App\Artisan;
use App\Evenement;
use App\Mail\Contact;
use Gloudemans\Shoppingcart\Facades\Cart;
use PHPUnit\Runner\Hook;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/',function(Request $request){
    return redirect()->route('caroussel.index');
});


//Route::group([],function(){


// Ca on garde
// mes routes pour l'ajout des articles
 Route::get('/create/{id_magasin}/article', 'Magasin_controller@createArticle');
 Route::post('/shop/{id_magasin}/article/store', 'Magasin_controller@storeArticle');
// Route pour la modification de l'article
 Route::get('/edit/{id_article}/{id_magasin}/article', 'Magasin_controller@editArticle');
 Route::put('/shop/{article}/article/update', 'Magasin_controller@updateArticle')->name('update_article');
 // route pour la suppression des articles
 Route::delete('/shop/{article}/article/delete','Magasin_controller@destroyArticle')->name('delete_article');

 // route pour les categorie
 
// c'est ton controlleur qui va encaisser toutes les routes
Route::resource('/shop','Magasin_controller');

// c'est ton controlleur qui va encaisser toutes les routes pour l'ajout de la categorie a propos de nous
Route::resource('/A_propos','Propo_controller');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Routes pour Artisan
Route::get('artisan','ArtisanController@index')->name('artisan.index');
Route::get('artisan/{id}','ArtisanController@show')->name('artisan.show');

// 2 route pour le formulaire de contact :
        Route::get('contact/create', 'Contact_controller@create')->name('contact.formulaire');
        Route::post('contact/store', 'Contact_controller@store')->name('contact.store');
        Route::get('contact/confirm', 'Contact_controller@confirm')->name('contact.confirm');
   
// route search
Route::get('search','SearchController@search')->name('shop.search');
// routes pour les evenements
Route::resource('/evenement','EvenementController');

// route pour la boutique
Route::resource('/boutique','ProduitController');
Route::get('/boutique/{slug}','ProduitController@show')->name('product.show');

Route::group(['middleware'=>['auth']],function(){
    // route pour les cartes
Route::get('/mon-panier','CartController@index')->name('cart.index');
Route::post('/panier/ajouter','CartController@store')->name('cart.store');
Route::patch('/panier/{rowId}','CartController@update')->name('cart.update');
Route::delete('/panier/{rowId}','CartController@destroy')->name('cart.destroy');
});
Route::group(['middleware'=>['auth']],function(){
// routes des checkout
Route::get('/paiement','CheckoutController@index')->name('checkout.index');
Route::post('/paiement','CheckoutController@store')->name('checkout.store');
Route::get('/merci','CheckoutController@thankyou')->name('checkout.merci');
});


// Route pour l'affichage du caroussel
Route::get('/accueil','CarousselController@affichecarou')->name('caroussel.index');

// Auth::routes();
Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
        Route::resource('users','UsersController');
        Route::resource('/shop','adminMagasinController');
        Route::resource('/evenement','adminEventController');
        Route::resource('/A_propos','adminPropoController');
        Route::resource('/contact','adminContactController');
        Route::resource('/article','adminArticleArtisanController');
        Route::get('contact/confirm','adminContactController@confirm')->name('contact.confirm');
        Route::resource('/caroussel','AdminCarousselController');
        Route::get('/',function(){
            return view('master.maitre_admin');
        });
        Route::get('/create/{id}/article', 'adminMagasinController@createArticle')->name('article.create.article');
        Route::post('/shop/{id}/article/store', 'adminMagasinController@storeArticle')->name('article.store.article');
       // Route pour la modification de l'article
        Route::get('/edit/{id}/{magasin_id}/article', 'adminMagasinController@editArticle')->name('article.edit.article');
        Route::put('/shop/{article}/article/update', 'adminMagasinController@updateArticle')->name('article.update.article');
        // route pour la suppression des articles
        Route::delete('/shop/{article}/article/delete','adminMagasinController@destroyArticle')->name('article.delete.article');
        Route::resource('/artisan','adminArtisanController');
        Route::get('/welcome','AdminCarousselController@affichecarou')->name('afficheCarou');
        Route::get('/search','SearchAdminController@searchAdmin')->name('search.search');
    
});

sitejess/app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
   
    protected $fillable = ['id','nom','email','sujet','message'];
}

sitejess/app/Http/Controllers/Contact_controller.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\ContactRequest;
use Illuminate\Support\Facades\Mail;
use App\Mail\Contact;
use App\Contact as ContactMessage;
use Illuminate\Http\Request;



class Contact_controller extends Controller
{
    // fonction pour la creation du formulaire de contact
    public function create(){
        return view('contact.create');
       
    }
    // fonction enregistre l'envoi d'un mail coté utilisateur
    public function store(Request $request){
    
       
        $validate = $request->validate([
            'nom'=>'required|min:3',
            'email'=>'required|email',
            'sujet'=>'required|between : 3,20',
            'message'=>'required'
        ]);
   
            $contact = ContactMessage::create($validate);

            Mail::to('ali@gmail.fr')
            ->send(new Contact($validate['nom'],$validate['email'],$validate['sujet'],$validate['message']));
            return redirect()->route('contact.confirm'); 
    }
    // fonction pour la confirmation d'envoi du mail
    public function confirm(){
        return view('contact.confirm');
    }
}

sitejess/resources/views/admin/contact/confirm.blade.php
@extends('master/maitre_admin')
@section('content')
<div class="container">
    <div >
        <h4 class="card-header">Contactez-Nous</h4>
        <div class="card-body">
            <p class="card-text">Merci. Votre message a été transmis à l'administrateur du site.
                 Vous recevrez une réponse rapidement.</p>
        </div>
    </div>
</div>

@endsection

sitejess/resources/views/admin/contact/create.blade.php
@extends('master/maitre')
@section('content')


    <div class="container">
         <div class="card">      {{-- class="row card text-white bg-dark"  sa c la couleur d'arriere plan en gris --}}
            <h4 >Contactez-Nous</h4>    {{-- class="card-header" sa c le soulignement et la case  --}}
            <div >
                <p>Vous avez une question, une demande … contactez-moi sur les réseaux sociaux 
                ( <a href="https://www.facebook.com/brestadresses" padding="50px"  target="_blank">https://www.facebook.com/brestadresses</a>  et 
                  <a href="https://www.instagram.com/brest_adresses/?hl=fr" target="_blank">https://www.instagram.com/brest_adresses/?hl=fr</a> ), 
                ou remplissez le formulaire suivant : </p>
            </div>
            <div class="card-body">
                <form action="{{route('contact.store') }}" method="POST">
                    @method("POST")
                    @csrf
                    <div class="form-group">
                        <label for="nom">Nom</label>
                        <input type="text" class="form-control  @error('nom') is-invalid @enderror" name="nom" id="nom" placeholder="Votre nom" value="{{ old('nom') }}">
                        @error('nom')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">E-Mail</label>
                        <input type="email" class="form-control  @error('email') is-invalid @enderror" name="email" id="email" placeholder="Votre email" value="{{ old('email') }}">
                        @error('email')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="sujet">Sujet</label>
                        <input type="text" class="form-control  @error('sujet') is-invalid @enderror" name="sujet" id="sujet" placeholder="sujet" value="{{ old('sujet') }}">
                        @error('sujet')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="text">Message</label>
                        <textarea class="form-control  @error('message') is-invalid @enderror" name="text" id="text" placeholder="Votre message">{{ old('text') }}</textarea>
                        @error('text')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>
                    <button type="submit" class="btn btn-secondary">Envoyer !</button>
                </form>
            </div>
            <div>
                <p> <strong>Partie pro</strong><br>  
                    Vous possédez un commerce brestois et vous souhaitez apparaître sur le site et sur les réseaux sociaux,
                     contactez-moi sur <a href="Mailto:brestadresses@gmail.com">brestadresses@gmail.com</a> . (Toutefois, afin de garder une cohérence sur la ligne éditoriale,
                      je serai en droit d’accepter, ou non, la publication de votre commerce.)
                    Vous souhaitez faire des photos ou collaborer avec Damien Peron, 
                    le photographe de Brest_adresses, contactez-le sur <a href="Mailto:perondamien22@gmail.com">perondamien22@gmail.com</a>  pour plus d’informations.</p>
            </div>
            

        </div>
    </div>
@endsection

sitejess/resources/views/admin/contact/message.blade.php
@extends('master/maitre_admin')
@section('content')
@if(session('supprimer'))
        <div class="alert alert-success">
            {{ session('supprimer') }}
        </div>
        @endif
<table class="table table-bordered">
    <thead>
      <tr>
        <th>#</th>
        <th>Nom</th>
        <th>E-Mail</th>
        <th>Sujet</th>
        <th>Message</th>
        <th>suppression</th>
      </tr>
    </thead>
    <tbody>
         @foreach ($contacts as $contact)
      <tr>
        <td>{{$contact->id}}</td>
        <td>{{$contact->nom}}</td>
        <td>{{$contact->email}}</td>
        <td>{{$contact->sujet}}</td>
        <td>{{$contact->message}}</td>
        <td>
            <form action="{{route('admin.contact.destroy',['contact' => $contact])}}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-outline-danger">Supprimer</button>
            </form>
        </td> 
      </tr>
    @endforeach
    </tbody>
  </table>
@endsection